package tests;

import helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Эвотор")
    void generatedTest() {
        step("Открываем url https://evotor.ru/", () -> {
            open("");

        step("На главной странице содержатся категории: 'Маркировка', 'Торговля алкоголем', " +
                "'Мобильный кассир', 'Номенклатурный учёт'");

        $("#grey-tiles").shouldHave(text("Маркировка"));

        $("#grey-tiles").shouldHave(text("Торговля алкоголем"));

        $("#grey-tiles").shouldHave(text("Мобильный кассир"));

        $("#grey-tiles").shouldHave(text("Номенклатурный учёт"));

        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Заголовок страницы должен содержать текст")
    void titleTest() {
        step("Open url 'https://evotor.ru/'", () ->
                open(""));

        step("Проверяем, что на главной странице есть текст 'Эвотор - официальный сайт | Онлайн-кассы для малого бизнеса от производителя'", () -> {
            String expectedTitle = "Эвотор - официальный сайт | Онлайн-кассы для малого бизнеса от производителя";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("В консоле браузера не должно быть ошибок")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://evotor.ru/'", () ->
                open(""));

        step("В консоли браузера не должно быть ошибок: 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}